### ISSUE TITLE
Output shows Angular CLI command but it does not run

### ISSUE THREAD

**Issue by endlessracingz** [cyrilletuzi/vscode-angular-schematics#56] opened 2019-08-20 23:33 UTC
The "Output" tab shows the Angluar CLI command but it does not run. If I copy and paste the command in to the "Terminal" tab it will run appropriately.

![image](https://user-images.githubusercontent.com/6493594/63391667-2964d580-c368-11e9-9093-656859e1249c.png)

![image](https://user-images.githubusercontent.com/6493594/63391681-3b467880-c368-11e9-9e3c-318483a7c0a7.png)

VSCode v1.37.1 on Windows 10
Angular CLI v8.2.2

**Comment by cyrilletuzi** [comment] 2019-08-21 08:50
Thanks for your feedback. But I can't reproduce the issue with the same config.

Can you tell me:
- your Node version?
- is Node installed the classic way or with a special tool like `nvm`?
- are you using a special / non-default shell/terminal?

**Comment by cyrilletuzi** [comment] 2019-09-08 18:04
As there is no news, I'm closing this issue for house-keeping. Feel free to comment and I'll reopen it.

**Comment by endlessracingz** [comment] 2019-09-09 16:19
Sorry I did not respond previously. The email notifications went in to my spam folder.

- Node v10.16.3
- Node installed the classic way
- I'm using powershell as the default terminal in VS Code

**Comment by cyrilletuzi** [comment] 2019-09-13 13:20
Unfortunately I can't reproduce this issue in a similar environment, and I have no idea why the command would hang.

Can you test with the beta version in #55?

**Comment by endlessracingz** [comment] 2019-09-13 20:18
I installed the beta version you linked and it is no longer hanging but I get this error:

![image](https://user-images.githubusercontent.com/6493594/64892321-f5a86300-d628-11e9-9467-f1e7cb114955.png)

**Comment by cyrilletuzi** [comment] 2019-09-15 09:04
Unfortunately I have no further idea how to debug your issue for now, so I'll leave the issue opened in case someone can help.

For v2, I'll explore again the solutions to run the commands, as using Node directly has caused a lot of issues, not just this one. I hope to find something which would fix this.

**Comment by cyrilletuzi** [comment] 2020-04-05 14:23
@endlessracingz Good news: your issue should be fixed by #125 

Can you follow the instructions in the PR to test and confirm the beta fixes your problem? Thanks.

**Closed** 2020-04-13 13:38 UTC
Labels: needs repro

**Comment by cyrilletuzi** [comment] 2020-04-13 13:48
For info: v4 has just been released and is a full rewrite of the extension. It should have fixed all weird cases like this one.

It took more than a *full-time* non-paid week to do this rewrite. Yet I still do not have any **[sponsor](https://github.com/sponsors/cyrilletuzi)**. So please consider to help, or to ask your enterprise, which makes money with this extension, to help.
