### ISSUE TITLE
Issue when a project path contains `projects`

### ISSUE THREAD

**Issue by Lightw3ight** [cyrilletuzi/vscode-angular-schematics#19] opened 2018-10-18 19:58 UTC
When I try to create a new component with vscode-angular-schematics, I get the error

`Error: Project '@xxx/env1' could not be found in workspace.`

The actual command that is being run is

`ng g component folder/new-thingy --project @xxx/env1`

The name of the project is xxx, im not sure where the @ or the env1 comes from

Running the following manually works fine

`ng g component folder/new-thingy --project xxx`

Currently running
Angular: 6.1.9
Angular CLI: 6.2.4
VS Code: 1.28.2

Thanks for taking the time to make this extension :)

**Comment by cyrilletuzi** [comment] 2018-10-19 07:44
@Lightw3ight The extension adds `--project` when the command is launched from a directory inside the `projects` directory, meaning a library (generated by `ng g library`) or a secondary application (generated by `ng g application`). Can you confirm in which precise situation you are?

**Comment by cyrilletuzi** [comment] 2018-10-25 20:18
@Lightw3ight ?

**Comment by cyrilletuzi** [comment] 2018-10-30 10:17
Closing as no new, feel free to comment if there is something new.

**Comment by michaeljota** [comment] 2019-01-28 20:41
@cyrilletuzi I'm having the same issue. Every time I try to create something with this in a folder, the command is created with `--project @parentFolder/projectFolder`. Maybe this should get the project from the `angular.json` or something? So far I've been unable to use this, but I still have it installed. :P

**Comment by cyrilletuzi** [comment] 2019-01-28 21:56
@michaeljota I can't reproduce your issue. I need a reproduction or at least more details about your directories structure.

**Comment by michaeljota** [comment] 2019-01-28 22:03
@cyrilletuzi 

Project Directory:
```powershell
> C:\projects\angular\my-storybook>
```

Command generated by VSCode Angular Schematics when selecting `Angular: Create a component` in context menu after right clicking in `app` folder.

```
ng g component component --project @angular/my-storybook
Project '@angular/my-storybook' could not be found in workspace.
Error: Project '@angular/my-storybook' could not be found in workspace.
    at Workspace._getProjectTool (c:\projects\angular\my-storybook\node_modules\@angular-devkit\core\src\workspace\workspace.js:189:19)
    at Workspace.getProjectSchematics (c:\projects\angular\my-storybook\node_modules\@angular-devkit\core\src\workspace\workspace.js:168:21)
    at Object.getSchematicDefaults (c:\projects\angular\my-storybook\node_modules\@angular\cli\utilities\config.js:263:34)
    at GenerateCommand.readDefaults (c:\projects\angular\my-storybook\node_modules\@angular\cli\models\schematic-command.js:356:35)
    at GenerateCommand.runSchematic (c:\projects\angular\my-storybook\node_modules\@angular\cli\models\schematic-command.js:125:37)
    at GenerateCommand.run (c:\projects\angular\my-storybook\node_modules\@angular\cli\commands\generate-impl.js:59:21)
    at Object.<anonymous> (c:\projects\angular\my-storybook\node_modules\@angular\cli\models\command-runner.js:180:24)
    at Generator.next (<anonymous>)
    at fulfilled (c:\projects\angular\my-storybook\node_modules\@angular\cli\models\command-runner.js:11:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Lightw3ight** [comment] 2019-01-29 01:48
Really sorry about not replying, I completly forgot about the issue

I just came back to trying to use the extension

This time I created a new app using the cli (Not a library), using the latest cli and angular
If I right click on any folder from `src/app` down and try to generate a component or module, it always appends the following to the command it intends to run
--@[Parent Folder]/[Project Folder]

For instance, if my project is located at
`c:\projects\MyWebsite\frontend`
And I follow the below steps
- Right click on the folder `c:\projects\MyWebsite\frontend\src\app`
- Select `Angular: Generate a module`
- Enter `abcdefg` for the path name
- Select `Classic module`

It will then attempt to run the following command

`ng g module abcdefg --project @MyWebsite\frontend`

**Comment by cyrilletuzi** [comment] 2019-01-29 07:46
Ok. When you generate a library with `ng g library` it goes in `projects/...`, a case the extension tries to detect.

So there is probably an issue in detection because your path contains `projects`. I'll quickly look at that to fix.

**Comment by michaeljota** [comment] 2019-01-29 15:09
I think this should relay more on the `angular.json` file. Even to activate itself automatically only when finding that file (or the old `.angular-cli.json`), and give the choose to activate it when not. 

The `angular.json` file has all the information needed about all the projects in the folder. The `projects` folder can be changed, and it could contain another applications as well.

**Comment by cyrilletuzi** [comment] 2019-01-29 17:39
Fixed in 1.12.2.

I opened #29 to add support for custom directories for libraries and multiple apps (I'll do that soon).

@Lightw3ight @michaeljota  Thanks for reporting. Please take just one minute to star [the extension on Visual Studio Code marketplace](https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.angular-schematics). 👍

**Closed by cyrilletuzi** 2019-01-29 17:39 UTC
Labels: bug

**Comment by cyrilletuzi** [comment] 2019-01-29 17:44
Btw, as you are working on Windows, if you have any idea to solve #27, it would be greatly appreciated.

**Comment by michaeljota** [comment] 2019-01-29 18:10
Thanks! Will look at it and see if I can help.

**Comment by Lightw3ight** [comment] 2019-01-29 18:48
Awesome, works perfectly :)
