### ISSUE TITLE
Support custom shells on Windows

### ISSUE THREAD

**Issue by Korbraan** [cyrilletuzi/vscode-angular-schematics#27] opened 2019-01-04 14:54 UTC
Hi!

I use Windows and WSL on my laptop, so I set the terminal.integrated.shell.windows setting to wsl.exe.
However, angular-schematics doesn't seem to use this setting as I have an error coming from cmd.exe.

Could you make the extension use the integrated shell setting on Windows so it will work with this kind of development environment?

**Comment by cyrilletuzi** [comment] 2019-01-04 15:13
This was done in #16, but because of an issue on Windows, I activated it for Mac and Linux only.

Can you try with version 1.8.0 (exactly) of this extension and tell me what happens?

Also, could you point me to steps to install and configure WSL, so I can do my own tests on my secondary computer?

**Comment by Korbraan** [comment] 2019-01-04 16:17
With version 1.8.0 I have another error but the extension use the right
shell.

An excellent article to install and configure WSL:
https://medium.com/@johnbwoodruff/epic-dev-environment-with-wsl-dc81e234ae61
(I use ZSH and nvm).

Le ven. 4 janv. 2019 à 16:13, Cyrille Tuzi <notifications@github.com> a
écrit :

**Comment by cyrilletuzi** [comment] 2019-01-04 18:09
So after investigation, it's because Node.js `exec` method pass `/d`, `/s`, `/c` as arguments to the shell on Windows, which is needed and works with the default shell, but seems to create issues with other shells. [Official documentation here](https://nodejs.org/api/child_process.html#child_process_shell_requirements) (chapter "Shell requirements" at the end).

I don't know how to solve this, so help welcomed.

**Comment by cyrilletuzi** [comment] 2019-01-04 18:44
@Korbraan To be sure: does the extension works on your Windows, even if it's not with your custom shell? If not, what is the error?

**Comment by Korbraan** [comment] 2019-01-07 10:09
I will look at these, but I need to set up a virtual environment so as not
to break my professional environment.

Thank you for your help, I will come back after some tests :)

Le ven. 4 janv. 2019 à 19:44, Cyrille Tuzi <notifications@github.com> a
écrit :

**Comment by michaeljota** [comment] 2019-01-30 15:36
@Korbraan They should not work with WSL, as this is a know issue. There is not issue reference, but is in the VSCode roadmap [WSL Support](https://github.com/Microsoft/vscode/wiki/Roadmap#wsl-support).

So far, extensions are not able to use the WSL, so this is not addressable right now, but maybe in a couple of months.

**Comment by cyrilletuzi** [comment] 2019-01-30 20:59
@michaeljota Thanks for you feedback but I don't think the issue is on the VS Code side. This extension uses the Node.js `exec` function to launch the CLI commands, and it's not working with Windows custom shells as the `exec` function auto-pass some args that seem incompatible with other shells than `cmd`. It's not even working with PowerShell, which seems quite strange.

**Comment by cyrilletuzi** [comment] 2019-08-08 20:19
@Korbraan @michaeljota Can you follow instructions in #56 and tell me if it solves this issue? The last VS Code update introduced a new API for extensions that may solve this problem.

**Comment by cyrilletuzi** [comment] 2019-08-10 12:18
Oops, the issue number was wrong so there was no link, it's #55.

**Comment by cyrilletuzi** [comment] 2020-04-05 14:26
Good news: this issue should be fixed by #125 (for real this time).

@Korbraan @michaeljota Can you follow the instructions in the PR to test and confirm the beta fixes the problem? Thanks.

**Closed** 2020-04-13 13:38 UTC
Labels: enhancement

**Comment by cyrilletuzi** [comment] 2020-04-13 13:52
For info: v4 has just been released and is a full rewrite of the extension. Now the CLI command is launched in VS Code Terminal, so the extension should not be affected by custom configuration on user side, as long as `ng g component hello` works in your *VS Code* Terminal.

It took more than a *full-time* non-paid week to do this rewrite. Yet I still do not have any **[sponsor](https://github.com/sponsors/cyrilletuzi)**. So please consider to help, or to ask your enterprise, which makes money with this extension, to help.
