### ISSUE TITLE
Feature: support for local-only CLI

### ISSUE THREAD

**Issue by merkuriy** [cyrilletuzi/vscode-angular-schematics#192] opened 2020-06-25 08:43 UTC
# Checks before posting an issue
<details><summary>RESULTS</summary>

- [x] I have read all the extension's documentation (README and docs/TROUBLESHOOTING)
- [x] My project meets the requirements indicated in README
- [x] I launched `ng g component hello` in the *VS Code* Terminal inside my project, and it works
- [x] I looked at the extension's logs ("Angular Schematics" Output channel, second tab left to the Terminal), and tried to fix my project's configuration accordingly
- [x] I understand I am writing to a *human being*, doing this open source project on his *free* time
- [x] I will be involved in my own issue, by answering questions and informing if the issue is resolved
</details>

# Configuration

- Ubuntu: 19.04
- VS Code: 1.46.1
- Angular CLI global (`ng version`): not installed
- Angular CLI local: 8.3.28
- Node: 12.11.1

# Description of the issue
AngularSchematics launch the global Angular CLI, not the local.

Related issues: #26

# How to reproduce the issue

AngularSchematics run: `ng g service shared/services/menu`
Result: `Command 'ng' not found, but can be installed with: sudo apt install ng-common`

Angular CLI Local is normal working:
```
./node_modules/.bin/ng g service shared/services/menu
npx ng g service shared/services/menu
yarn ng g service shared/services/menu
```

**Comment by cyrilletuzi** [comment] 2020-08-12 15:50
So, there is already history about this.

In a previous version, I introduced the use of the local CLI directly (`./node_modules/.bin/ng g`), but as this command contains special characters, it resulted in issues in some specific shell installations (#27).

That is why I reverted to the usage of the global CLI (`ng g`) in version 4.

However, before v4, Node `exec` function was used to launch commands. Since v4, the VS Code Terminal is used, so maybe the special characters issue would be gone.

But v4 introduced other features that makes such a feature less trivial to reimplement now: advanced workspaces are now supported (for example, `.bin/ng` could be in a parent directory).

So I think it is not worth it. Again:
- this is the recommandation of the official Angular documentation,
- it is really simple and quick to install the CLI globally,
- doing `ng g` directly still uses the local CLI.

Do you see a use case where installing the CLI globally is an issue?

If not, I will close this issue as working as intended. Someone can still do a Pull Request, but it should:
- check it does not reintroduce #27 issue,
- it works for all kind of workspaces.

**Comment by cyrilletuzi** [comment] 2020-08-27 12:08
Closing this issue for house-keeping as there is no news. Feel free to answer and I will open it back.

**Comment by starikovs** [comment] 2020-11-06 14:54
Hey guys!

I also would like to have local `ng` support. Probably instead of `./node_modules/.bin/ng g` the `npx ng g` can be used, which has the same behavior if you have `ng` installed locally and don't have it globally.

**Comment by cyrilletuzi** [comment] 2020-11-06 15:30
Unfortunately it is not that easy:
- `npx` seems deprecated in npm v7, in favor of `npm exec`
- some users don't use npm but yarn instead

**Comment by cyrilletuzi** [comment] 2020-11-07 08:03
I'll reopen this issue, but this feature needs a solution working with all configurations to be implemented.

**Closed** 2021-02-12 16:34 UTC
Labels: enhancement, help wanted
