### ISSUE TITLE
Editor format settings are being ignored or overwritten?

### ISSUE THREAD

**Issue by elementalPRESS** [cyrilletuzi/vscode-angular-schematics#161] opened 2020-05-20 15:59 UTC
At first: Thank you very much for this great extension. It saved me so much time until now. Awesome work!

But there is a small problem with the created files. Let me try to explain: my editor settings are e.g. Tab = 4 and do not replace tabs with spaces. When I create now a component with your extension the newly created files have a tabsize of 2 and tabs are filled with spaces. 

This wouldn't be a big problem but I cannot change this again. I'm using prettier to auto format on save, but there is nothing happened. Any kind of auto format is not applied to files created with the extension.

Do you have any idea or solution to fix this behaviour?

Thx and best greets,
Lars

**Comment by cyrilletuzi** [comment] 2020-05-20 16:08
> At first: Thank you very much for this great extension. It saved me so much time until now. Awesome work!

Thanks. :)

> But there is a small problem with the created files.

The extension is not creating any files at all: it only launches an Angular CLI command, which then creates the files. So I suppose if you do `ng g component` directly in your terminal you also have 2 spaces indentation, right?

> Any kind of auto format is not applied to files created with the extension.

You mean that even if you do a change in the file and save, Prettier is not doing its job?

If so, is that still happening if you close VS Code and open it again?

**Comment by elementalPRESS** [comment] 2020-05-20 18:37
> You mean that even if you do a change in the file and save, Prettier is not doing its job?

It does, but with wrong settings...

> If so, is that still happening if you close VS Code and open it again?

I tried this and that worked well. So I need to close VS Code and open it again to get the correct format. Strange...

**Comment by cyrilletuzi** [comment] 2020-05-20 19:37
I can't reproduce your issue. I've tried to reproduce by:
- `ng new demo`
- `cd demo`
- `npm install prettier --save-dev --save-exact`
- change `indent_size` to `4` in `.editorconfig`
- set `"editor.formatOnSave": true` in VS Code preferences
- install the Prettier VS Code extension (`esbenp.prettier-vscode`)
- generate a component with the extension
- save: it works (indentation is changed to 4 spaces)

So I need additional information:
- your OS
- your VS Code version
- your Prettier VS Code extension (`esbenp.prettier-vscode`) version
- your `prettier` dependency version (in `node_modules`)
- your Prettier configuration
- the values of `editor.formatOnSave` and `editor.defaultFormatter` in your VS Code preferences

**Comment by cyrilletuzi** [comment] 2020-06-08 19:55
Closing this issue for house keeping, as there is no news from 3 weeks. Feel free to comment and I will reopen the issue.

**Closed by cyrilletuzi** 2020-06-08 19:55 UTC
Labels: needs repro
